server:
  port: 8080

app:
  security:
    jwt:
      secret-key: ${APP_SECURITY_JWT_SECRET_KEY:srssecret}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://db-mysql-sfo3-68208-do-user-3594963-0.b.db.ondigitalocean.com:25060/wscevents?createDatabaseIfNotExist=true
    username: events-admin
    password: AVNS_LtF9DibUJEIO_j-ZoYX

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        format_sql: true
  flyway:
    locations:
      - classpath:db/migration/dev
    enabled: off
    baseline-on-migrate: off

logging:
  file:
    name: script/integration_log.log
  level:
    springframework:
      web: DEBUG
      data: DEBUG
    boot:
      autoconfigure:
        data:
          rest: DEBUG
          jpa: DEBUG
          orm: DEBUG
